# Generated by Django 5.2.7 on 2025-10-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='On-site', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='experience_level',
            field=models.CharField(choices=[('Entry', 'Entry Level'), ('Mid', 'Mid Level'), ('Senior', 'Senior Level'), ('Manager', 'Manager')], default='Entry', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Remote', 'Remote')], default='Full-time', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='remote_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
